language: node_js

node_js: "8"

script: npm run compile

# deploy:
#   provider: netlify
#   site: 63089d2f-46a6-40e5-a019-d957c172b2f2
#   auth: $NETLIFY_AUTH
#   dir: dist
#   edge: true # opt in to dpl v2
#   on:
#     branch: stable