language: node_js
node_js: "10"

addons:
  chrome: stable

before_install:
  - npm install -g @lhci/cli@0.3.x

script:
  - npm run compile
  - lhci autorun --assert.preset=lighthouse:recommended --upload.target=temporary-public-storage

# deploy:
#   provider: netlify
#   site: 63089d2f-46a6-40e5-a019-d957c172b2f2
#   auth: $NETLIFY_AUTH
#   dir: dist
#   edge: true # opt in to dpl v2
#   on:
#     branch: stable