# netlify.toml

[build]
  command = "npm run compile"
  publish = "dist"

[dev]
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/coming-soon"

[[redirects]]
  from = "/progress"
  to = "https://github.com/GreenhouseTech/DevMe/blob/stable/CHANGELOG.md"

[[redirects]]
  from = "/newsletter"
  to = "https://eepurl.com/gMir_r"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true