# netlify.toml

[build]
  command = "npm run pack"
  publish = "dist"

[dev]
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/coming-soon"

[[redirects]]
  from = "/progress"
  to = "https://headwayapp.co/devme-changelog"
  
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true